language: php
php:
  - 8.0
# env:
#   matrix:
#     - TRAVIS_NODE_VERSION="10"
#     - TRAVIS_NODE_VERSION="11"
#     - TRAVIS_NODE_VERSION="12"

# blocklist
# branches:
#   except:
#   - /^Deploy\s.*$/
matrix:
  fast_finish: true
# before_install:
#   - '. $HOME/.nvm/nvm.sh'
#   - nvm install $TRAVIS_NODE_VERSION
#   - nvm use $TRAVIS_NODE_VERSION
#   - npm install -g npm@latest
before_install:
  # Disable xdebug.
  - nvm install v20.15.1
  - nvm use v20.15.1
  - npm install -g npm@10.7.0
install:
  - npm install
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - php --version
  - node --version
  - npm --version
script:
  - npm run build:drupal --if-present

after_success: 
   - git add .
   - git commit -m "[skip travis] Adding particle dist/ assets"
  #  - git push https://bmartinez287:${GITHUB_API_KEY}@${GH_REF} HEAD:develop  #clownvary is my username on github, you need to use yourself , do not use travis or others.

deploy:
  provider: pages
  edge: true
  target_branch: develop 
  github-token: ${GITHUB_API_KEY}  # Your GitHub token set in Travis CI console
  on:
    branch: develop
  verbose: true
  commit_message: "[skip travis] Deploying Compiled Assets [skip travis-ci]"